FROM python:3.8-slim-buster

WORKDIR /app

COPY CloudCode/python/requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY CloudCode/python/ .

CMD ["python3", "-u", "virtual_device_rest_service.py"]