apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-server
  labels:
    app: iot-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-server
  template:
    metadata:
      labels:
        app: iot-server
    spec:
      containers:
        - name: iot-server
          image: guilhermefaleiros/iot-server:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi
