apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-web
  labels:
    app: iot-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-web
  template:
    metadata:
      labels:
        app: iot-web
    spec:
      containers:
        - name: iot-web
          image: guilhermefaleiros/iot-web:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi
