# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iot_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11iot_service.proto\x12\x0biot_service\"\x0f\n\rDeviceRequest\"7\n\x0b\x44\x65viceReply\x12(\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x17.iot_service.DeviceItem\"I\n\nDeviceItem\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\"(\n\x12TemperatureRequest\x12\x12\n\nsensorName\x18\x01 \x01(\t\"\'\n\x10TemperatureReply\x12\x13\n\x0btemperature\x18\x01 \x01(\t\"-\n\nLedRequest\x12\x10\n\x08\x64\x65viceId\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\"l\n\x08LedReply\x12\x31\n\x06\x64\x65vice\x18\x01 \x03(\x0b\x32!.iot_service.LedReply.DeviceEntry\x1a-\n\x0b\x44\x65viceEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xe4\x01\n\nIoTService\x12R\n\x0eSayTemperature\x12\x1f.iot_service.TemperatureRequest\x1a\x1d.iot_service.TemperatureReply\"\x00\x12<\n\x08\x42linkLed\x12\x17.iot_service.LedRequest\x1a\x15.iot_service.LedReply\"\x00\x12\x44\n\nGetDevices\x12\x1a.iot_service.DeviceRequest\x1a\x18.iot_service.DeviceReply\"\x00\x42\x37\n\x1bio.grpc.examples.iotserviceB\x0fIoTServiceProtoP\x01\xa2\x02\x04TEMPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iot_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.iotserviceB\017IoTServiceProtoP\001\242\002\004TEMP'
  _LEDREPLY_DEVICEENTRY._options = None
  _LEDREPLY_DEVICEENTRY._serialized_options = b'8\001'
  _DEVICEREQUEST._serialized_start=34
  _DEVICEREQUEST._serialized_end=49
  _DEVICEREPLY._serialized_start=51
  _DEVICEREPLY._serialized_end=106
  _DEVICEITEM._serialized_start=108
  _DEVICEITEM._serialized_end=181
  _TEMPERATUREREQUEST._serialized_start=183
  _TEMPERATUREREQUEST._serialized_end=223
  _TEMPERATUREREPLY._serialized_start=225
  _TEMPERATUREREPLY._serialized_end=264
  _LEDREQUEST._serialized_start=266
  _LEDREQUEST._serialized_end=311
  _LEDREPLY._serialized_start=313
  _LEDREPLY._serialized_end=421
  _LEDREPLY_DEVICEENTRY._serialized_start=376
  _LEDREPLY_DEVICEENTRY._serialized_end=421
  _IOTSERVICE._serialized_start=424
  _IOTSERVICE._serialized_end=652
# @@protoc_insertion_point(module_scope)
